# Generated by Django 4.2.7 on 2023-11-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=45, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=45, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.PositiveIntegerField(verbose_name='Segundo Apellido')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('rol', models.CharField(choices=[('AD', 'Administrador'), ('VE', 'Vendedor'), ('AL', 'Almacenista')], max_length=2, verbose_name='Rol')),
                ('direccion', models.CharField(max_length=45, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=45, verbose_name='Ciudad')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extrangería')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.PositiveIntegerField(unique=True, verbose_name='Documento')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
